# This file was generated by GoReleaser. DO NOT EDIT.
class Oauth2t < Formula
  desc "Access Token helper for OAuth2 comms."
  homepage "https://github.com/Contrast-Security-Inc/oauth2t"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Contrast-Security-Inc/oauth2t/releases/download/v0.0.2/oauth2t_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "900a2bc5507f9a49c83296da58d129c9d6c650f93375853cc60511825b5cec5f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Contrast-Security-Inc/oauth2t/releases/download/v0.0.2/oauth2t_0.0.2_Linux_x86_64.tar.gz"
      sha256 "6c954592983b24a712445fe63dcdc3773b2cca765f61a59e1dcd2202de5973ac"
    end
  end

  def install
    bin.install "oauth2t"
  end
end
