# This file was generated by GoReleaser. DO NOT EDIT.
class Oauth2t < Formula
  desc "OAuth2 client helper tool for access token management."
  homepage ""
  version "v0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Contrast-Security-Inc/oauth2t/releases/download/v0.0.1/oauth2t_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "34465d8219036924f0d4ca4e5ac769c18e3236b1a7ead664c70ba78900e316ea"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Contrast-Security-Inc/oauth2t/releases/download/v0.0.1/oauth2t_0.0.1_Linux_x86_64.tar.gz"
      sha256 "8671f3df6248821ba601a3d29307bc61c4ad70401ce84b30e02a62aab5b0a898"
    end
  end

  def install
    bin.install "oauth2t"
  end
end
